# Generated by Django 5.0.6 on 2024-06-03 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(default=None)),
                ('icon', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('discount', models.BooleanField(default=False, verbose_name='تخفیف')),
                ('image', models.ImageField(blank=True, default=True, null=True, upload_to='product_image', verbose_name='تصویر محصول')),
                ('old_price', models.FloatField(default=99.99, verbose_name='قیمت اصلی')),
                ('slug', models.SlugField(default=None)),
                ('inventory', models.IntegerField(default=0, verbose_name='موجودی')),
                ('top_deal', models.BooleanField(default=False)),
                ('flash_sale', models.BooleanField(default=False)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.category', verbose_name='دسته بندی')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='featured_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storeapp.products'),
        ),
    ]
