# Generated by Django 5.0.6 on 2024-06-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='flash_sale',
        ),
        migrations.RemoveField(
            model_name='products',
            name='top_deal',
        ),
    ]
