# Generated by Django 5.0.6 on 2024-06-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_remove_products_discount_remove_products_flash_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='تخفیف'),
        ),
    ]
