# Generated by Django 5.0.6 on 2024-06-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_rename_discription_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='flash_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='top_deal',
            field=models.BooleanField(default=False),
        ),
    ]
