# Generated by Django 5.0.6 on 2024-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_products_flash_sale_products_top_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image', verbose_name='تصویر محصول'),
        ),
    ]
